[phases.setup]
nixPkgs = ["python311Full", "nodejs-18_x"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"
